server:
  port: 8761
spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF